export const goToSignupPage = (navigator) => navigator ('/signup')
export const goToBuscarPage = (navigator) => navigator ('/buscar')
export const goToCadastroPage = (navigator) => navigator ('/cadastro')
export const goToEditarPage = (navigator) => navigator ('/editar')
export const goToFeedPage = (navigator) => navigator ('/feed')
export const goToLoginPage = (navigator) => navigator ('/')
export const goToMeuCarrinhoPage = (navigator, id) => navigator (`/meu_carrinho/${id}`)
export const goToMeuPerfilPage = (navigator) => navigator ('/meu_perfil')
export const goToResultadoPage = (navigator, id) => navigator (`/resultado/${id}`)